import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import { Be_Vietnam_Pro } from "next/font/google";
import "@/app/scss/main.css";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import component
import Header from "@/app/components/user/layout/Header";
import Footer from "@/app/components/user/layout/Footer";
import AccountSidebar from "@/app/components/user/AccountSidebar";
import userServiceServer from "@/app/services/userService-server";
import { TypeUserInfo } from "@/app/types/user";

// root layout
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // save cart login

  return (
    <html lang="en">
      <body className={`${beVietnamPro.variable} antialiased`}>
        {/* <Header /> */}
        {/* <main> */}
        <section className="section--user section-py">
          <div className="container">
            <div className="row">
              <AccountSidebar />
              <div className="col-9">{children}</div>
            </div>
          </div>
        </section>
        {/* <ToastContainer
            position="top-right"
            autoClose={1500}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnHover
            draggable
            theme="light"
          />
        </main>
        <Footer /> */}
      </body>
    </html>
  );
}
