import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import { Be_Vietnam_Pro } from "next/font/google";
import "@/app/scss/main.css";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import component
import Footer from "@/app/components/user/layout/Footer";
import AsideMenu from "./asideMenu";
import Header from "@/app/components/seller/layout/Header";

// root layout
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // save cart login

  return (
    <html lang="en">
      <body className={`${beVietnamPro.variable} antialiased`}>
        {/* <SaveCarLogin />
        <Header /> */}
        <div className="seller--layout flex flex-col h-screen">
          <Header />
          <div className="layout--main flex flex-1 w-full">
            <AsideMenu />
            <main className="flex-1 flex flex-col  bg-neutral-50">
              <div className="scroll flex-[1_1_0] p-6 overflow-y-auto">
                {children}
                <ToastContainer
                  position="top-right"
                  autoClose={1500}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  pauseOnHover
                  draggable
                  theme="light"
                />
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
