import type { Metadata } from "next";

import { Be_Vietnam_Pro } from "next/font/google";
import "@/app/scss/main.css";
import { ToastContainer } from "react-toastify";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

// import component
import Footer from "@/app/components/user/layout/Footer";

// root layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${beVietnamPro.variable} antialiased`}>
        <main className="w-full h-[100dvh] relative overflow-hidden bg-[#4E9BFF] py-10 -mb-10">
          {children}
          <ToastContainer
            position="top-right"
            autoClose={1500}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnHover
            draggable
            theme="light"
          />
          <div className="bg--authIcon icon1"></div>
          <div className="bg--authIcon icon2"></div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
