import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import { Be_Vietnam_Pro } from "next/font/google";
import "@/app/scss/main.css";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import cartServices from "../services/cartServices";

// import component
import Header from "../components/user/layout/Header";
import Footer from "@/app/components/user/layout/Footer";
import { ApiError } from "../types/type";
import SaveCarLogin from "./SaveCarLogin";

// root layout
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // save cart login

  return (
    <html lang="en">
      <body className={`${beVietnamPro.variable} antialiased`}>
        <SaveCarLogin />
        <Header />
        <main>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={1500}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnHover
            draggable
            theme="light"
          />
        </main>

        <Footer />
      </body>
    </html>
  );
}
